project_id = "ojcvtfwuscitrrhloqhu"

[functions.notify-vendor]
verify_jwt = false

[functions.get-product]
verify_jwt = false

[functions.checkout-api]
verify_jwt = false

[functions.meetpay-webhook]
verify_jwt = false

[functions.admin-api]
verify_jwt = false
