// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const HARDCODED_SUPABASE_URL = 'https://dqclmqbegnimtbkndrif.supabase.co';
const HARDCODED_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxY2xtcWJlZ25pbXRia25kcmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5NjE4NzMsImV4cCI6MjEwMTUzNzg3M30.pemKTzkeYqSOtiVGwCWx5uzXyITJLnCCVVBacPGvalo';

// The two Winger applications share this one backend. Keeping the URL/key pair
// canonical prevents stale Vercel variables from selecting a legacy project.
const SUPABASE_URL = HARDCODED_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = HARDCODED_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
